project_id = "ilptklvdbuhvtasjxcdc"

[functions.crypto-prices]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.generate-image]
verify_jwt = true

[functions.extract-ocr]
verify_jwt = true
